name: oath_client
description: "플러터로 만든 약속지킴이 클라이언트"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  # 더 넓은 버전 범위 허용
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  freezed_annotation: ^2.4.1 # freezed 로 생성된 코드를 위한 의존성
  dio: ^5.9.0

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  flutter_naver_map: ^1.4.1+1
  flutter_secure_storage: ^9.2.2
  image_picker: ^1.2.0
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9     # 코드 생성을 실행하는 패키지
  freezed: ^2.5.2          # freezed 코드 생성기
  json_serializable: ^6.8.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/images/logo.jpg
